### ISSUE TITLE
Is the test application supposed to do anything?

### ISSUE THREAD

**Issue by BOLL7708** [artumino/SteamVR_HUDCenter#2]
So I'm trying to push my own notifications through OpenVR, and this is about the only project that actually has code for it in C#. Sadly the code does not seem to work with the latest versions of the C# wrapper, and building the test application in the repo gives me a form that seemingly does nothing but log mouse clicks... ?

Has [this](https://github.com/artumino/SteamVR_HUDCenter/blob/master/SteamVR_HUDCenter/HUDCenterController.cs#L118-L139) code been working before?

As it was nine months since the last update I'm guessing this is a dead project, but I figured I could leave a note here anyway as I've been trying to figure this out for many months now :P Cheers!

**Comment by artumino** [comment]
Hey, yes the project is inactive at the moment. I've been busy and I have
little to no time to keep it updated.

With every OpenVR update I need to add some Handles that aren't included by
Valve in the C# wrapper to access notifications (specifically the one used
in the code that you highlited).

The test application it's supposed to mirror a form to an overlay in
steamvr and emulate mouse events with the motion controller.

I'll commit some changes and update to the latest OpenVR version. I noticed
that there's still a version of SteamVr.cs from the unity plugin in the
project since it has no purpose I'll remove that too.
Once I'll have more time I'll try to make a more meaningfull​ example
project and I'll find a better way to patch the handles needed in the
wrapper.

**Comment by BOLL7708** [comment]
Thanks for replying :) Cross-referencing code all over the place I actually managed to get a wee bit forward this weekend, or at least that's what I think. I'll probably take it easy for a while but [this](https://steamcommunity.com/app/358720/discussions/0/333656722986468756/#c133259227529435259) is the last result. No idea how to fix it or what I've forgotten but yeah, at least _something_ is happening.

I'll spend some time checking out your openvr_api.cs, had no idea you had actually modified it :) Cheers!

**Comment by artumino** [comment]
I pushed a commit with the new wrapper and I also generated a diff patch between Valve's version and the one used in the project. I don't know why they left those methods out.

The test application still has some issues with mouse event simulation but the notification api should be    good to go.

**Comment by BOLL7708** [comment]
I do use the NuGet package, is that an involved process to update or can it be connected to GitHub? I see the release branch has 0.0.3 but from NuGet I still get 0.0.0.2 ?

**Comment by BOLL7708** [comment]
As a side note, Valve finally added notifications to the C# header after I [poked](https://github.com/ValveSoftware/openvr/issues/1016#issue-404923841) them again. 😁
